version: '3.9'

services:
  nextcloud:
    image: nextcloud
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - E:/Readonly:/mnt/storage1
      - D:/writable:/mnt/storage2
    environment:
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=nextcloudpass
      - MYSQL_HOST=nextcloud-db
    depends_on:
      - nextcloud-db

  nextcloud-db:
    image: mariadb
    container_name: nextcloud-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=rootpass
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextclouduser
      - MYSQL_PASSWORD=nextcloudpass
    volumes:
      - db_data:/var/lib/mysql

  nextcloud-redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped

volumes:
  nextcloud_data:
  db_data:
